- src/StepMania.cpp
If you start openitg with a working directory other than that of the parent of the executable, patch data will fail to load. Which will among other problems cause a crash when entering options. 
The problem was that we tried to mount a relative physical path after checking that it exists against the VFS.
The solution is to keep the check against the VFS and then extract the absolute physical path to the checked virtual path using ResolvePath.
The bug does not occur on arcade builds.
I haven’t not tested arcade or windows builds.
I have tested mounting patches with both relative and absolute paths. The parameters sent to FILEMAN::Mount() are the same now as before, provided your current working directory was the same as the parent of the executable.
PATCH_DIR is no longer needed, which is …
> Fixed a bug where patch data would not get loaded

- src/RageSurfaceUtils.cpp
- src/archutils/Win32/arch_setup.h
lrintf is now provided by the windows sdk. We need to conditionally exclude the openitg implementation for it to build.
> Fix compile error on VS 2013 (lrintf)

- src/RageDisplay_D3D.cpp
- src/RageUtil.cpp
- src/arch/InputHandler/InputHandler_DirectInput.cpp
- src/arch/InputHandler/InputHandler_DirectInputHelper.cpp
- src/arch/InputHandler/InputHandler_DirectInputHelper.h
This migrates the Direct 3D and DirectInput related code to DirectX 9. DirectX 8 headers and libs are hard to find these days and with DX9 at least SM5 and OpenITG share the same dependency, making the threshold for developing OpenITG somewhat lower.
DirectX 9 libs can be found in the following SDK: https://www.microsoft.com/en-us/download/details.aspx?id=6812 
Tested on windows 8.1. I ran through most screens I could think of, took screenshots, changed graphics settings etc. Seems to be working fine.
Since DX9 is also so old I dont think we will have any compatibility issues with older versions of windows. Hopefully people aren't running OpenITG on versions earlier than Windows XP.
> Migrate to DirectX 9

- src/SongManager.cpp
Reloading songs in the options menu crashes the game 100% of the time.
After deleting all objects in m_pSongs, FreeSongs() left the list full of NULL values causing a crash later when searching for songs in that list.
> Fixed crash when reloading songs

- configure.ac
The goal is to make the package configuration run better on modern linux aswell as the older debian sarge used to build itg arcade compatible binaries.
I'm starting with updates to configure.ac for newer versions of autoconf. The changes are also backwards compatible with the sarge environment, I tested to make sure.
> Updates to autotools scripts

- src/ScreenSelectMusic.cpp
Requested by MadMatt here: http://www.aaronin.jp/boards/viewtopic.php?p=477190#477190
And by Zetorux here: http://www.aaronin.jp/boards/viewtopic.php?p=470894#470894
I think its a sensible change, this way we dont reset the rate mod just like we dont reset other options. Its also a behavioral difference between openitg and 3.95/itg2. Themes may rely on the fact that the rate mod is not reset. 
Simply love does exactly that and it causes the displayed rate mod to get out of sync with the actually used rate mod. But only in openitg.
> Dont reset rate mod between songs

- src/ScoreKeeperMAX2.cpp
In ScoreKeeperMAX2.cpp, iCurPossibleDancePoints would grow at least twice as fast as your actual dance points, which means getting a fantastic will still subtract from your score. You always end up with 0% at the end of the song. This was easily reproduced by enabling subtractive scoring in PlayerOptions.cpp:36
`m_ScoreDisplay = SCORING_SUBTRACT;`
I also logged the resulting dance points after each call to HandleTapRowScore. This is from a chart with 4 notes. iCurPossibleDancePoints makes no sense.
> iPossibleDancePoints = 35, iCurPossibleDancePoints = 10, iActualDancePoints = 0
> iPossibleDancePoints = 35, iCurPossibleDancePoints = 30, iActualDancePoints = 10
> iPossibleDancePoints = 35, iCurPossibleDancePoints = 50, iActualDancePoints = 20
> iPossibleDancePoints = 35, …
> Fixed subtractive scoring

- src/LuaReference.cpp
- src/LuaReference.h
Found this while debugging the theme switch crash. It's a separate bug and Im not sure if it is ever a problem. 
I reproduced it by switching themes in Simply love. The game crashed because of an assert in OptionRowHandler.cpp:836
`ASSERT( lua_gettop(L) == 0 );`
OptionRowHandlerLua::ExportOption expects the lua stack to be empty. Because SetFromNil() never pops the stack, values from failed RunScript invocations are left on the stack.
> Pop lua stack after RunScript fails

- configure.ac
Running configure with multiple git tags caused config.h to get corrupted. git tag outputs multiple lines which is not expected by the code.
We would get a macro definition without a closing quote:
#define BUILD_VERSION "beta3
Which later causes a compile error.
git describe --abbrev=0 does what we want. It gets only the latest tag on short form (only the tag name).
> Compile error with multiple git tags

- src/ScreenUserPacks.cpp
- src/SongManager.cpp
- src/StepMania.cpp
- src/UserPackManager.cpp
- src/arch/ArchHooks/ArchHooks_Unix.cpp
Consolidated the responsibility of /itgdata to where it is mounted in the VFS. This way users of the VFS wont have to have intimate knowledge of whether the underlying fs is writable or not.
This does open up /itgdata for writing more than previously, and we might want to keep that to a minimum. But as I see it, that ship has sailed.
This change brings a few advantages:
* Cleaner code. Knowledge of mount options wont have to be spread out across the codebase.
* Respects changes a user might have done in /etc/fstab. For example this: http://aaronin.jp/boards/viewtopic.php?t=10760
* The arcade build is more tolerant towards different system configurations, making running openitg easier.
* Backwards compatibility is preserved.
> Conditionally remount /itgdata as writable only once during startup

- chroot-arcade.sh
Added libncurses5-dev to the list of packages to install in an arcade chroot environment.
This is needed for running "make menuconfig" when compiling the linux kernel, which is something you might do when working on openitg.
(gettext was removed because it was in the list twice)
> Add libncurses5-dev to list of chroot packages

- autoconf/m4/ffmpeg.m4
- build-arcade.sh
- configure.ac
- src/Makefile.am
- src/arch/MovieTexture/FFMpeg_Helper_Common.h
- src/arch/MovieTexture/FFMpeg_Helper_Legacy.cpp
- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
- src/arch/MovieTexture/Selector_MovieTexture.h
These are some ffmpeg autoconf improvements I had lying around that were pretty useless without a major refactoring of the ffmpeg movie driver code. Now that @spigwitmer has taken care of that I dusted off this code.
This PR adds two new options to configure:
1. --without-ffmpeg
2. --with-legacy-ffmpeg
Because ffmpeg is so unstable these new options allow us more flexibility when building. We can explicitly specify which ffmpeg to build against, or if we want to build it at all.
--with-legacy-ffmpeg allows us to separate the behavior --enable-itg-arcade changes from its build requirements. The latter are best defined in build-arcade.sh.
I've also defined a new macro HAVE_LEGACY_FFMPEG. HAVE_FFMPEG used to mean "we are building against system ffmpeg libraries", while it being undefined …
> ffmpeg autoconf improvements

- src/LuaManager.cpp
As reported in issue #41 by @concubidated, openitg crashes on startup with simply love as the default theme. This is because the theme sets preferences by doing:
```
[Preferences]
SoloSingle=@PREFSMAN:GetPreference('SoloSingle')
```
The lua expression evaluates to a boolean which cannot be converted to a string by lua_tostring, so it returns NULL.
The crash occurs in LuaManager.cpp on the line that reads:
`sOut = lua_tostring( L, -1 );`
In beta2, assigning null to a CString would produce an empty string.
In beta3 and master we get a null pointer exception.
The regression happened in commit e54e5c0959299034dfd7f594877805f536bfb7d3. StdString.h was updated to what I assume was a newer version. The new version no longer contained a null check, which ignored null pointers (in ssasn):
```
// …
```
> Fixed crash when Simply Love sets preferences during startup

- src/SongUtil.cpp
For some reason the loop at SongUtil.cpp:126 did not respect its condition and kept going with larger and larger value of 'g' until it crashed.
Most likely it has to do with a newer compiler optimization. It doesn't happen on older versions of gcc nor does it happen in debug mode. But I don't know the exact details.
This closes #36
> Fixed crash at ScreenSelectMusic

- src/Preference.h
- src/PrefsManager.cpp
- src/PrefsManager.h
- src/ScreenOptionsMaster.cpp
- src/ScreenOptionsMasterPrefs.cpp
- src/StepMania.cpp
- src/ThemeManager.cpp
Fixed a crash that would happen anytime the theme is changed using the standard option row metric "conf,Theme". The bug affects virtually all themes including Simply love and GrooveNights. The only theme i found that did not have the bug is the default theme. It has a custom theme switcher which circumvents the problem with "conf,Theme".
The problem was that all option rows are saved in the order they are showed on screen. Saving the theme option causes an immediate theme switch which unloads all lua scripts the previous theme had loaded.
When the following option row is saved it will fail and crash if it calls a lua function that was unloaded. The introduction of Theme as a preference does not change the fact that GamePrefs.ini stores what theme is actually supposed to be used. This …
> Switch theme crash

- assets/patch-data/Themes/default/Languages/english.ini
- assets/patch-data/Themes/default/Scripts/LuaPrefs.lua
- assets/patch-data/Themes/default/metrics.ini
Removed CustomsLoadMax, CustomMaxSizeMB, CustomMaxStepSizeKB and AllowExtraPlayerOptions. They were previously removed from PrefsManager.cpp but not from the theme.
Backwards compatibility is preserved by keeping the lua functions but returning dummy option rows. Themes using the deprecated lua functions wont crash.
> Removed unused custom song options 

- assets/patch-data/Themes/default/Graphics/_award models/flag materials orange.txt
If you get 1 excellent on a song the evaluation screen will show a green flag instead of an orange flag. The award for 1 excellent referred to an orange flag in the default theme but the material for the orange flag was green. This bug exists in the default theme in stock ITG2.
This is what it looks like in stock itg2 https://www.youtube.com/watch?v=ikI51b9pnNA 
(i just searched for "1 ex itg" and picked a random video confirming the bug. I assume they run stock itg2)
> 1 excellent award is a green flag at the evaluation screen

- src/ScoreKeeperMAX2.cpp
Simple change that replaces a few ints with int64_t. Zetorux did an amazing job both finding the bug and laying out the technical details behind it.
Recreated the bug by making a 500 bpm chart filled with 48,000 notes with 64th spacing. Putting openitg on AutoPlayCPU crashed the game within 20 notes.
Verified that the above chart played all the way through after applying the fix.
Verified that it builds for both home and arcade on Debian i386.
This closes #44
> Fixed crash on very long charts caused by MAX2 scoring calculation

- assets/patch-data/Themes/fallback/Scripts/Sprite.lua
This bug as well as the fix was reported by Zetorux.
If the second song (or a later song) in a marathon does not have a valid background openitg crashes with the message:
> Error: [string "/Themes/fallback/Scripts/Sprite.lua"]:13: calling `GetPath' on bad self (number expected, got nil)
Simply love and many other themes have already fixed this bug in their own copies of Sprite.lua. So the bug is fairly contained to the default theme.
Sprite.lua calls THEME:GetPath with ELEMENT_CATEGORY_GRAPHICS as the first argument. If we check ThemeManager.h we can see it's actually supposed to be EC_GRAPHICS.
There are no other references to ELEMENT_CATEGORY_GRAPHICS.
> Fixed crash when a song is missing a background in a marathon

- src/ScreenTextEntry.cpp
this was most likely broken by the StdString update eons ago as the behavior of CString assignments to NULL changed
> ScreenTextEntry: fix traversal and BitmapText value population

- assets/patch-data/Themes/default/BGAnimations/ScreenDemonstration2 underlay/default.xml
- assets/patch-data/Themes/default/BGAnimations/ScreenGameplay underlay/default.xml
- src/GameState.cpp
- src/ScreenDemonstration.cpp
Reported by Zetorux.
ScreenDemonstration inherits from ScreenJukebox and relies on it to set a random song during init.
If no song is found that meet the requirements of ScreenJukebox::SetSong() GAMESTATE->m_pCurSong will be left as NULL, which causes a few lua conditions to fail. For instance this one in ScreenGameplay:
`GAMESTATE:IsHumanPlayer(PLAYER_1) and GAMESTATE:GetPlayMode()==PLAY_MODE_REGULAR and GAMESTATE:GetCurrentSteps(PLAYER_1):GetDifficulty()==DIFFICULTY_BEGINNER`
GAMESTATE:GetCurrentSteps(PLAYER_1) will be null when the song is null causing this error:
Dialog: "Lua runtime error parsing "return GAMESTATE:IsHumanPlayer(PLAYER_1) and 
> GAMESTATE:GetPlayMode()==PLAY_MODE_REGULAR and GAMESTATE:GetCurrentSteps(PLAYER_1):GetDifficulty()==DIFFICULTY_BEGINNER": [string "in"]:1: …
> Lua error in ScreenDemonstration

- src/arch/MovieTexture/FFMpeg_Helper.cpp
- src/arch/MovieTexture/FFMpeg_Helper.h
- src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
- src/global.h
the CR for this looks messed up because it has a dependency on the gcc6+ffmpeg 16-bit depth fix.
To reproduce:
* run OpenITG
* press enter to skip to the title screen
* wait for about 15-20 seconds and observe the red square horizon whateveritis background movie freezing
The fix has been tested on ffmpeg 3.0 and legacy.
> Fix MovieTexture_FFMpeg failing to rewind

- common.sh
has_file failed to warn about missing itg2-util because the command "file" always had exit code 0.
Using "if [ -f $1 ]; then" is probably more portable.
> Fixed gen-arcade-patch.sh failing in a clean repository

- assets/patch-data/Themes/default/Languages/english.ini
- assets/patch-data/Themes/default/Scripts/Other.lua
- src/ScreenUserPacks.cpp
The old behavior hardcoded the cancel and wait messages in ::Init() if they weren't available as a theme metric (and they aren't in the default theme's english.ini). When these hardcoded strings were used, they weren't evaluated by ThemeManager (see `ThemeManager::EvaluateString()`) in the same manner as ones taken from a language file, so dumb things happened. We could set `bAlwaysReload` for those ThemeMetric instances, but really I'm not sure if they belong hardcoded in ::Init() in the first place.
> Fix issue #27: ScreenUserPacks menu button tokens not expanded

- src/arch/MemoryCard/MemoryCardDriverThreaded_Linux.cpp
- src/arch/MemoryCard/MemoryCardDriverThreaded_Linux.h
Set "UsePmount=1" in stepmania.ini to use pmount instead of fstab and mount to mount memory cards. pmount only exists for debian based linux distributions.
Two changes have been made:
* Fixed device name leak when using pmount for memory cards. When mounting a memory card the device is mounted write checked and unmounted. The unmount always failed, causing a device name leak. A lack of the -l parameter for pmount was the cause. The actual parameter for pmount is nowadays "--yes-I-really-want-lazy-unmount" (advertising danger).
* Because of the dangers of "-l", p/umount will now retry instead of using -l immediately. -l is used as a last resort.
> Fixed device name leak when using pmount for memory cards

- assets/game-data/Themes/home/metrics.ini
Updated help text in ScreenUserPacks that referred to the wrong location on an USB drive.
UserPackManager.h has the correct path in a macro.
> Updated help text in ScreenUserPacks

- src/arch/ArchHooks/ArchHooks_Unix.cpp
Mounting ~/.openitg for home builds enables openitg to be installed in /opt or /usr without requiring the user to have write permission to the game content.
Any file read from /opt will have its modifications written to ~/.openitg. Upon subsequent reads the modified file will be read.
This change is already made through a custom patch with various alterations by everyone who maintains a package of stepmania or its derivatives.
For the packaging process of openitg to be as smooth as possible it's best to make this change "upstream". This is very related to the docker build system I've been working on.
SM5 mounts ~/.stepmania-5.0 by default since a while back.
> Mount a VFS root in ~/.openitg for home builds

- configure.ac
This is a dependency for #75. My dependency, at least.
`have_libresample` was checked against a value of `no`, one which it never gets set to. Because of this, builds have just fell back on the default make target to configure libresample. Hilarity ensued during the openSUSE docker build because it runs `make clean` right after `./configure`, which would be before a Makefile for libresample even exists yet.
> fix broken logic for libresample check in configure.ac

- configure.ac
- src/RageSurface_Load_PNG.cpp
In libpng 1.4 accessing io_ptr and error_ptr directly in png_struct was deprecated. Png_struct no longer exposes those members. Instead we are supposed to use accessor functions exported by libpng. The ones we need existed as far back as version 1.2. With these changes we are therefore compatible with libpng 1.2 all through to the latest version (1.6 as of now).
The change to configure.ac fixes a bug where the second try to detect “png” never succeeded. That block was entered when have_libpng=no, but it was never changed to yes. So detection always failed.
Tested manually on OpenSUSE 42.1
- With libpng 1.6.8
- With libpng 1.2.50
Also tested on Arch linux, but only that it builds.
All builds using the new docker build system succeeded
- Arcade machine revision
- Opensuse
- Ubuntu
Verified …
> libpng 1.6 compatibility

- autoconf/m4/ffmpeg.m4
This will check for ffmpeg 2.0 during configuration. I'm not sure exactly what version we require at the moment, but i do know that 0.5.2 (the previous requirement) is too old.
Recent versions of most distros now have at least version 2.7 of ffmpeg.
I've also fixed a couple mistakes in the pkgconfig code.
> Require ffmpeg 2.0

- assets/patch-data/Themes/default/BGAnimations/_ITG credits text.xml
I don't know what encoding the file has now, but it's not UTF-8. And the only text view so far to display the file correctly is the github differ.
I re-added an UTF-8 BOM to the itg2 credits file and fixed invalid characters. The original file in d4.zip has a BOM and is valid UTF-8. The current one was not.
Example: http://i63.tinypic.com/hskpxf.jpg
> ITG2 credits displays smiley faces instead of quotes around nicknames

- README
- ReleaseNotes.txt
- changelog.txt
I have updated the changelog, release notes and readme to reflect the changes since the large batch of commits by @vyhd february 7th 2013.
**beta 3**
I set the release date to february 7th 2013 since:
- These were the last changes by vyhd and were followed by a long period of project inactivity
- The releases he made early 2013 were still under the beta 3 version
**beta 4**
I combined beta 3 and beta 4 into beta 3 with the same reasoning as above. Even though beta 4 was recorded in the changelog, WIP releases were still made as "beta 3". Beta 4 was therefore killed.
**0.9**
This is what I chose to call everything developed since early 2013. It can be renamed. No release date has been set.
**README**
I removed two TODO entries from the README. With the changes made during 2016, I think we …
> Release notes for beta 3, beta 4 and 0.9

- src/RageFileManager.cpp
Fixes a bug in RageFileManager::ResolvePath which adds a / before all returned physical paths causing the patch data to not get loaded on windows.
This is tested on windows and linux with both patch.zip and a patch folder. With both opengl and d3d.
I've also tested that the bug fixed in PR #47 stays fixed.
Closes #87
> Windows patch mount

- src/ActorUtil.cpp
- src/RageTextureManager.cpp
Tested on windows with VS 2015 and the new ffmpeg libs.
If ffmpeg cant play the file it will simply ignore it and show a black background.
The crash happens when there are unmapped file types used as backgrounds in songs.
> Added support for playing mp4 and mkv files as song backgrounds

- build/build-arcade-machine-revision.sh
- gen-arcade-patch.sh
Testing on an actual dedicab with the help of Rodent we ran into a problem where after installing the machine revision you would get a verification failure of subsequent revisions signed with the same key.
It turns out the official openitg path.rsa is checked into the repo.
To fix this the new build scripts will require both the private and the public key when signing a machine revision. Makes sure machine revisions from the same source can be installed without copying a new Patch.rsa to the machine every time.
> Machine revision verification failure

- gen-arcade-patch.sh
- gen-patch-zip.sh
this is hindering creating machine revisions, and failing silently at that with the stdout redirection.
i'm not even sure what those lines in gen-patch-zip.sh are trying to accomplish past cd'ing into and out of a directory. if there's more to this syntax than I see feel free to school me, but bash is properly equipped to handle such situations more elegantly. that last sentence was some sick accidental poetry.  mom's spaghetti.
such changes were applied to gen-arcade-patch.sh as well.
testing done:
```
$ ls artifacts
'ITG 2 OpenITG-0.9rc1.itg'
$ unzip -l artifacts/*
Archive:  artifacts/ITG 2 OpenITG-0.9rc1.itg
Length      Date    Time    Name
---------  ---------- -----   ----
271  2016-04-15 22:07   install-patch.sh
0  2017-03-30 20:13   modules/
31594  2017-03-30 20:13 …
```
> fix confusing and/or erroneous syntax in gen-arcade-patch and gen-patch-zip

- build/build-source-package.sh
this just ensures the .git folder or .gitignore files don't end up in the source package.
testing done (note: the 0.9rc1 tag doesn't exist yet remotely, it's created on my end for testing):
```
$ tar -Jtf artifacts/openitg-0.9rc1+1+g8df595fd.tar.xz | grep '\.git'
$ git checkout master
$ ./build-source-package.sh ./artifacts
...
$ tar -Jtf artifacts/openitg-0.9rc1.tar.xz | grep '\.git'
openitg-0.9rc1/src/libtommath/.gitignore
openitg-0.9rc1/.gitignore
...
openitg-0.9rc1/.git/objects/for/years
...
$
```
> exclude .git folder and related files from source distribution

- README-Windows-build.md
- README.md
- src/GameState.cpp
- src/GameState.h
- src/HTTPHelper.cpp
- src/HTTPHelper.h
- src/Makefile.am
- src/MsdFile.cpp
- src/MsdFile.h
- src/ProfileManager.cpp
- src/ProfileManager.h
- src/ScreenGameplay.cpp
- src/ScreenPackages.cpp
- src/ScreenPackages.h
- src/StepMania-net2010.vcxproj
- src/StepMania-net2010.vcxproj.filters
- src/arch/MemoryCard/MemoryCardDriverThreaded_Windows.cpp
- src/ezsockets.cpp
- src/ezsockets.h
- src/io/P3IO.cpp
- src/io/P3IO.h
This PR removes my debug device from the p3io code and makes it less chatty in the log reducing log spam and disk thrashing and io bottlenecking. The statements won't help anyone anyway and were only meant to be temporary. I left them there so people could understand what the code was doing, however, in case someone else wanted to write an IO driver for it.
Also adds the ability to add a defined timeout to ezsockets, abstracts the http logic from screenpackages, and allows it to be used to, for example, broadcast the current song being played. I also added the ability to thread these requests so the game thread isn't lagged. The end result will be nice for streamers and allow enhanced functionality in the future (I'll be making a score broadcaster as well, great for tournaments and …
> Performance and Network enhancements

- README-Windows-build.md
- README.md
Documentation on building for windows in the readme, and how to build the dependencies in the windows specific readme. Includes google-sanctioned workaround for modern ffmpeg FAST_CLZ detection.
> Update windows build documentation

- build/build-all.sh
- build/build-arcade-machine-revision.sh
- gen-arcade-patch.sh
- src/arch/COM/impl/list_ports/list_ports_linux.cc
* during patch building in the arcade build, the public key is required as a param for gen-arcade-patch.sh but not passed through the build scripts. gen-arcade-patch now just extracts it from the private key.
* g++ 3.3 was not a fan of that raii one-liner in list_ports_linux.cc for whatever reason
> fix arcade build params and compile errors
